// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.cscotta.deschutes.example.requests;

public final class Requests {
  private Requests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 timestamp = 1;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    long getTimestamp();

    // required int32 serverId = 2;
    /**
     * <code>required int32 serverId = 2;</code>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 2;</code>
     */
    int getServerId();

    // required int32 userId = 3;
    /**
     * <code>required int32 userId = 3;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 3;</code>
     */
    int getUserId();

    // required int32 clientIp = 4;
    /**
     * <code>required int32 clientIp = 4;</code>
     */
    boolean hasClientIp();
    /**
     * <code>required int32 clientIp = 4;</code>
     */
    int getClientIp();

    // required int32 serverIp = 5;
    /**
     * <code>required int32 serverIp = 5;</code>
     */
    boolean hasServerIp();
    /**
     * <code>required int32 serverIp = 5;</code>
     */
    int getServerIp();

    // required .analytics.Request.OperationType operationType = 6;
    /**
     * <code>required .analytics.Request.OperationType operationType = 6;</code>
     */
    boolean hasOperationType();
    /**
     * <code>required .analytics.Request.OperationType operationType = 6;</code>
     */
    com.cscotta.deschutes.example.requests.Requests.Request.OperationType getOperationType();

    // required .analytics.Request.Protocol protocol = 7;
    /**
     * <code>required .analytics.Request.Protocol protocol = 7;</code>
     */
    boolean hasProtocol();
    /**
     * <code>required .analytics.Request.Protocol protocol = 7;</code>
     */
    com.cscotta.deschutes.example.requests.Requests.Request.Protocol getProtocol();

    // required int32 responseCode = 8;
    /**
     * <code>required int32 responseCode = 8;</code>
     */
    boolean hasResponseCode();
    /**
     * <code>required int32 responseCode = 8;</code>
     */
    int getResponseCode();

    // required string uri = 9;
    /**
     * <code>required string uri = 9;</code>
     */
    boolean hasUri();
    /**
     * <code>required string uri = 9;</code>
     */
    java.lang.String getUri();
    /**
     * <code>required string uri = 9;</code>
     */
    com.google.protobuf.ByteString
        getUriBytes();

    // required int32 requestBytes = 10;
    /**
     * <code>required int32 requestBytes = 10;</code>
     */
    boolean hasRequestBytes();
    /**
     * <code>required int32 requestBytes = 10;</code>
     */
    int getRequestBytes();

    // required int32 responseBytes = 11;
    /**
     * <code>required int32 responseBytes = 11;</code>
     */
    boolean hasResponseBytes();
    /**
     * <code>required int32 responseBytes = 11;</code>
     */
    int getResponseBytes();

    // required int64 handshakeUsec = 12;
    /**
     * <code>required int64 handshakeUsec = 12;</code>
     */
    boolean hasHandshakeUsec();
    /**
     * <code>required int64 handshakeUsec = 12;</code>
     */
    long getHandshakeUsec();

    // required int64 usecToFirstByte = 13;
    /**
     * <code>required int64 usecToFirstByte = 13;</code>
     */
    boolean hasUsecToFirstByte();
    /**
     * <code>required int64 usecToFirstByte = 13;</code>
     */
    long getUsecToFirstByte();

    // required int64 usecTotal = 14;
    /**
     * <code>required int64 usecTotal = 14;</code>
     */
    boolean hasUsecTotal();
    /**
     * <code>required int64 usecTotal = 14;</code>
     */
    long getUsecTotal();

    // optional string userAgent = 15;
    /**
     * <code>optional string userAgent = 15;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string userAgent = 15;</code>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string userAgent = 15;</code>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    // optional string locale = 16;
    /**
     * <code>optional string locale = 16;</code>
     */
    boolean hasLocale();
    /**
     * <code>optional string locale = 16;</code>
     */
    java.lang.String getLocale();
    /**
     * <code>optional string locale = 16;</code>
     */
    com.google.protobuf.ByteString
        getLocaleBytes();

    // optional string referrer = 17;
    /**
     * <code>optional string referrer = 17;</code>
     */
    boolean hasReferrer();
    /**
     * <code>optional string referrer = 17;</code>
     */
    java.lang.String getReferrer();
    /**
     * <code>optional string referrer = 17;</code>
     */
    com.google.protobuf.ByteString
        getReferrerBytes();
  }
  /**
   * Protobuf type {@code analytics.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timestamp_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serverId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              userId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              clientIp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              serverIp_ = input.readInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.cscotta.deschutes.example.requests.Requests.Request.OperationType value = com.cscotta.deschutes.example.requests.Requests.Request.OperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                operationType_ = value;
              }
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.cscotta.deschutes.example.requests.Requests.Request.Protocol value = com.cscotta.deschutes.example.requests.Requests.Request.Protocol.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                protocol_ = value;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              responseCode_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              uri_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              requestBytes_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              responseBytes_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              handshakeUsec_ = input.readInt64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              usecToFirstByte_ = input.readInt64();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              usecTotal_ = input.readInt64();
              break;
            }
            case 122: {
              bitField0_ |= 0x00004000;
              userAgent_ = input.readBytes();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              locale_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              referrer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cscotta.deschutes.example.requests.Requests.internal_static_analytics_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cscotta.deschutes.example.requests.Requests.internal_static_analytics_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cscotta.deschutes.example.requests.Requests.Request.class, com.cscotta.deschutes.example.requests.Requests.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code analytics.Request.Protocol}
     */
    public enum Protocol
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HTTP = 0;</code>
       */
      HTTP(0, 0),
      /**
       * <code>HTTPS = 1;</code>
       */
      HTTPS(1, 1),
      /**
       * <code>SPDY = 2;</code>
       */
      SPDY(2, 2),
      /**
       * <code>QUIC = 3;</code>
       */
      QUIC(3, 3),
      ;

      /**
       * <code>HTTP = 0;</code>
       */
      public static final int HTTP_VALUE = 0;
      /**
       * <code>HTTPS = 1;</code>
       */
      public static final int HTTPS_VALUE = 1;
      /**
       * <code>SPDY = 2;</code>
       */
      public static final int SPDY_VALUE = 2;
      /**
       * <code>QUIC = 3;</code>
       */
      public static final int QUIC_VALUE = 3;


      public final int getNumber() { return value; }

      public static Protocol valueOf(int value) {
        switch (value) {
          case 0: return HTTP;
          case 1: return HTTPS;
          case 2: return SPDY;
          case 3: return QUIC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Protocol>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Protocol>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Protocol>() {
              public Protocol findValueByNumber(int number) {
                return Protocol.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.cscotta.deschutes.example.requests.Requests.Request.getDescriptor().getEnumTypes().get(0);
      }

      private static final Protocol[] VALUES = values();

      public static Protocol valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Protocol(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:analytics.Request.Protocol)
    }

    /**
     * Protobuf enum {@code analytics.Request.OperationType}
     */
    public enum OperationType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET = 0;</code>
       */
      GET(0, 0),
      /**
       * <code>PUT = 1;</code>
       */
      PUT(1, 1),
      /**
       * <code>DELETE = 2;</code>
       */
      DELETE(2, 2),
      ;

      /**
       * <code>GET = 0;</code>
       */
      public static final int GET_VALUE = 0;
      /**
       * <code>PUT = 1;</code>
       */
      public static final int PUT_VALUE = 1;
      /**
       * <code>DELETE = 2;</code>
       */
      public static final int DELETE_VALUE = 2;


      public final int getNumber() { return value; }

      public static OperationType valueOf(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return PUT;
          case 2: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
              public OperationType findValueByNumber(int number) {
                return OperationType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.cscotta.deschutes.example.requests.Requests.Request.getDescriptor().getEnumTypes().get(1);
      }

      private static final OperationType[] VALUES = values();

      public static OperationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private OperationType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:analytics.Request.OperationType)
    }

    private int bitField0_;
    // required int64 timestamp = 1;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required int32 serverId = 2;
    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_;
    /**
     * <code>required int32 serverId = 2;</code>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 serverId = 2;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    // required int32 userId = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private int userId_;
    /**
     * <code>required int32 userId = 3;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 userId = 3;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // required int32 clientIp = 4;
    public static final int CLIENTIP_FIELD_NUMBER = 4;
    private int clientIp_;
    /**
     * <code>required int32 clientIp = 4;</code>
     */
    public boolean hasClientIp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 clientIp = 4;</code>
     */
    public int getClientIp() {
      return clientIp_;
    }

    // required int32 serverIp = 5;
    public static final int SERVERIP_FIELD_NUMBER = 5;
    private int serverIp_;
    /**
     * <code>required int32 serverIp = 5;</code>
     */
    public boolean hasServerIp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 serverIp = 5;</code>
     */
    public int getServerIp() {
      return serverIp_;
    }

    // required .analytics.Request.OperationType operationType = 6;
    public static final int OPERATIONTYPE_FIELD_NUMBER = 6;
    private com.cscotta.deschutes.example.requests.Requests.Request.OperationType operationType_;
    /**
     * <code>required .analytics.Request.OperationType operationType = 6;</code>
     */
    public boolean hasOperationType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .analytics.Request.OperationType operationType = 6;</code>
     */
    public com.cscotta.deschutes.example.requests.Requests.Request.OperationType getOperationType() {
      return operationType_;
    }

    // required .analytics.Request.Protocol protocol = 7;
    public static final int PROTOCOL_FIELD_NUMBER = 7;
    private com.cscotta.deschutes.example.requests.Requests.Request.Protocol protocol_;
    /**
     * <code>required .analytics.Request.Protocol protocol = 7;</code>
     */
    public boolean hasProtocol() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .analytics.Request.Protocol protocol = 7;</code>
     */
    public com.cscotta.deschutes.example.requests.Requests.Request.Protocol getProtocol() {
      return protocol_;
    }

    // required int32 responseCode = 8;
    public static final int RESPONSECODE_FIELD_NUMBER = 8;
    private int responseCode_;
    /**
     * <code>required int32 responseCode = 8;</code>
     */
    public boolean hasResponseCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 responseCode = 8;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    // required string uri = 9;
    public static final int URI_FIELD_NUMBER = 9;
    private java.lang.Object uri_;
    /**
     * <code>required string uri = 9;</code>
     */
    public boolean hasUri() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string uri = 9;</code>
     */
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uri = 9;</code>
     */
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 requestBytes = 10;
    public static final int REQUESTBYTES_FIELD_NUMBER = 10;
    private int requestBytes_;
    /**
     * <code>required int32 requestBytes = 10;</code>
     */
    public boolean hasRequestBytes() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 requestBytes = 10;</code>
     */
    public int getRequestBytes() {
      return requestBytes_;
    }

    // required int32 responseBytes = 11;
    public static final int RESPONSEBYTES_FIELD_NUMBER = 11;
    private int responseBytes_;
    /**
     * <code>required int32 responseBytes = 11;</code>
     */
    public boolean hasResponseBytes() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 responseBytes = 11;</code>
     */
    public int getResponseBytes() {
      return responseBytes_;
    }

    // required int64 handshakeUsec = 12;
    public static final int HANDSHAKEUSEC_FIELD_NUMBER = 12;
    private long handshakeUsec_;
    /**
     * <code>required int64 handshakeUsec = 12;</code>
     */
    public boolean hasHandshakeUsec() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required int64 handshakeUsec = 12;</code>
     */
    public long getHandshakeUsec() {
      return handshakeUsec_;
    }

    // required int64 usecToFirstByte = 13;
    public static final int USECTOFIRSTBYTE_FIELD_NUMBER = 13;
    private long usecToFirstByte_;
    /**
     * <code>required int64 usecToFirstByte = 13;</code>
     */
    public boolean hasUsecToFirstByte() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int64 usecToFirstByte = 13;</code>
     */
    public long getUsecToFirstByte() {
      return usecToFirstByte_;
    }

    // required int64 usecTotal = 14;
    public static final int USECTOTAL_FIELD_NUMBER = 14;
    private long usecTotal_;
    /**
     * <code>required int64 usecTotal = 14;</code>
     */
    public boolean hasUsecTotal() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>required int64 usecTotal = 14;</code>
     */
    public long getUsecTotal() {
      return usecTotal_;
    }

    // optional string userAgent = 15;
    public static final int USERAGENT_FIELD_NUMBER = 15;
    private java.lang.Object userAgent_;
    /**
     * <code>optional string userAgent = 15;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional string userAgent = 15;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userAgent = 15;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string locale = 16;
    public static final int LOCALE_FIELD_NUMBER = 16;
    private java.lang.Object locale_;
    /**
     * <code>optional string locale = 16;</code>
     */
    public boolean hasLocale() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string locale = 16;</code>
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          locale_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string locale = 16;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string referrer = 17;
    public static final int REFERRER_FIELD_NUMBER = 17;
    private java.lang.Object referrer_;
    /**
     * <code>optional string referrer = 17;</code>
     */
    public boolean hasReferrer() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional string referrer = 17;</code>
     */
    public java.lang.String getReferrer() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referrer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string referrer = 17;</code>
     */
    public com.google.protobuf.ByteString
        getReferrerBytes() {
      java.lang.Object ref = referrer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referrer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      timestamp_ = 0L;
      serverId_ = 0;
      userId_ = 0;
      clientIp_ = 0;
      serverIp_ = 0;
      operationType_ = com.cscotta.deschutes.example.requests.Requests.Request.OperationType.GET;
      protocol_ = com.cscotta.deschutes.example.requests.Requests.Request.Protocol.HTTP;
      responseCode_ = 0;
      uri_ = "";
      requestBytes_ = 0;
      responseBytes_ = 0;
      handshakeUsec_ = 0L;
      usecToFirstByte_ = 0L;
      usecTotal_ = 0L;
      userAgent_ = "";
      locale_ = "";
      referrer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperationType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtocol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUri()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRequestBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResponseBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHandshakeUsec()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsecToFirstByte()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUsecTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, clientIp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, serverIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, operationType_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, protocol_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, responseCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getUriBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, requestBytes_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, responseBytes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(12, handshakeUsec_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(13, usecToFirstByte_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, usecTotal_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBytes(15, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getLocaleBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getReferrerBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, clientIp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverIp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, operationType_.getNumber());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, protocol_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, responseCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getUriBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, requestBytes_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, responseBytes_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, handshakeUsec_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, usecToFirstByte_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, usecTotal_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getLocaleBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getReferrerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.cscotta.deschutes.example.requests.Requests.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cscotta.deschutes.example.requests.Requests.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code analytics.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cscotta.deschutes.example.requests.Requests.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cscotta.deschutes.example.requests.Requests.internal_static_analytics_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cscotta.deschutes.example.requests.Requests.internal_static_analytics_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cscotta.deschutes.example.requests.Requests.Request.class, com.cscotta.deschutes.example.requests.Requests.Request.Builder.class);
      }

      // Construct using com.cscotta.deschutes.example.requests.Requests.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        clientIp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverIp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        operationType_ = com.cscotta.deschutes.example.requests.Requests.Request.OperationType.GET;
        bitField0_ = (bitField0_ & ~0x00000020);
        protocol_ = com.cscotta.deschutes.example.requests.Requests.Request.Protocol.HTTP;
        bitField0_ = (bitField0_ & ~0x00000040);
        responseCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        uri_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        requestBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        responseBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        handshakeUsec_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        usecToFirstByte_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        usecTotal_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00004000);
        locale_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        referrer_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cscotta.deschutes.example.requests.Requests.internal_static_analytics_Request_descriptor;
      }

      public com.cscotta.deschutes.example.requests.Requests.Request getDefaultInstanceForType() {
        return com.cscotta.deschutes.example.requests.Requests.Request.getDefaultInstance();
      }

      public com.cscotta.deschutes.example.requests.Requests.Request build() {
        com.cscotta.deschutes.example.requests.Requests.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.cscotta.deschutes.example.requests.Requests.Request buildPartial() {
        com.cscotta.deschutes.example.requests.Requests.Request result = new com.cscotta.deschutes.example.requests.Requests.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientIp_ = clientIp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serverIp_ = serverIp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.operationType_ = operationType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.protocol_ = protocol_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.responseCode_ = responseCode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.uri_ = uri_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.requestBytes_ = requestBytes_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.responseBytes_ = responseBytes_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.handshakeUsec_ = handshakeUsec_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.usecToFirstByte_ = usecToFirstByte_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.usecTotal_ = usecTotal_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.locale_ = locale_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.referrer_ = referrer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cscotta.deschutes.example.requests.Requests.Request) {
          return mergeFrom((com.cscotta.deschutes.example.requests.Requests.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cscotta.deschutes.example.requests.Requests.Request other) {
        if (other == com.cscotta.deschutes.example.requests.Requests.Request.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasClientIp()) {
          setClientIp(other.getClientIp());
        }
        if (other.hasServerIp()) {
          setServerIp(other.getServerIp());
        }
        if (other.hasOperationType()) {
          setOperationType(other.getOperationType());
        }
        if (other.hasProtocol()) {
          setProtocol(other.getProtocol());
        }
        if (other.hasResponseCode()) {
          setResponseCode(other.getResponseCode());
        }
        if (other.hasUri()) {
          bitField0_ |= 0x00000100;
          uri_ = other.uri_;
          onChanged();
        }
        if (other.hasRequestBytes()) {
          setRequestBytes(other.getRequestBytes());
        }
        if (other.hasResponseBytes()) {
          setResponseBytes(other.getResponseBytes());
        }
        if (other.hasHandshakeUsec()) {
          setHandshakeUsec(other.getHandshakeUsec());
        }
        if (other.hasUsecToFirstByte()) {
          setUsecToFirstByte(other.getUsecToFirstByte());
        }
        if (other.hasUsecTotal()) {
          setUsecTotal(other.getUsecTotal());
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00004000;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasLocale()) {
          bitField0_ |= 0x00008000;
          locale_ = other.locale_;
          onChanged();
        }
        if (other.hasReferrer()) {
          bitField0_ |= 0x00010000;
          referrer_ = other.referrer_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasUserId()) {
          
          return false;
        }
        if (!hasClientIp()) {
          
          return false;
        }
        if (!hasServerIp()) {
          
          return false;
        }
        if (!hasOperationType()) {
          
          return false;
        }
        if (!hasProtocol()) {
          
          return false;
        }
        if (!hasResponseCode()) {
          
          return false;
        }
        if (!hasUri()) {
          
          return false;
        }
        if (!hasRequestBytes()) {
          
          return false;
        }
        if (!hasResponseBytes()) {
          
          return false;
        }
        if (!hasHandshakeUsec()) {
          
          return false;
        }
        if (!hasUsecToFirstByte()) {
          
          return false;
        }
        if (!hasUsecTotal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cscotta.deschutes.example.requests.Requests.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cscotta.deschutes.example.requests.Requests.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 timestamp = 1;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required int32 serverId = 2;
      private int serverId_ ;
      /**
       * <code>required int32 serverId = 2;</code>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 serverId = 2;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 2;</code>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000002;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 2;</code>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // required int32 userId = 3;
      private int userId_ ;
      /**
       * <code>required int32 userId = 3;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000004;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 3;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0;
        onChanged();
        return this;
      }

      // required int32 clientIp = 4;
      private int clientIp_ ;
      /**
       * <code>required int32 clientIp = 4;</code>
       */
      public boolean hasClientIp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 clientIp = 4;</code>
       */
      public int getClientIp() {
        return clientIp_;
      }
      /**
       * <code>required int32 clientIp = 4;</code>
       */
      public Builder setClientIp(int value) {
        bitField0_ |= 0x00000008;
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 clientIp = 4;</code>
       */
      public Builder clearClientIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientIp_ = 0;
        onChanged();
        return this;
      }

      // required int32 serverIp = 5;
      private int serverIp_ ;
      /**
       * <code>required int32 serverIp = 5;</code>
       */
      public boolean hasServerIp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 serverIp = 5;</code>
       */
      public int getServerIp() {
        return serverIp_;
      }
      /**
       * <code>required int32 serverIp = 5;</code>
       */
      public Builder setServerIp(int value) {
        bitField0_ |= 0x00000010;
        serverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverIp = 5;</code>
       */
      public Builder clearServerIp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverIp_ = 0;
        onChanged();
        return this;
      }

      // required .analytics.Request.OperationType operationType = 6;
      private com.cscotta.deschutes.example.requests.Requests.Request.OperationType operationType_ = com.cscotta.deschutes.example.requests.Requests.Request.OperationType.GET;
      /**
       * <code>required .analytics.Request.OperationType operationType = 6;</code>
       */
      public boolean hasOperationType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .analytics.Request.OperationType operationType = 6;</code>
       */
      public com.cscotta.deschutes.example.requests.Requests.Request.OperationType getOperationType() {
        return operationType_;
      }
      /**
       * <code>required .analytics.Request.OperationType operationType = 6;</code>
       */
      public Builder setOperationType(com.cscotta.deschutes.example.requests.Requests.Request.OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        operationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .analytics.Request.OperationType operationType = 6;</code>
       */
      public Builder clearOperationType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        operationType_ = com.cscotta.deschutes.example.requests.Requests.Request.OperationType.GET;
        onChanged();
        return this;
      }

      // required .analytics.Request.Protocol protocol = 7;
      private com.cscotta.deschutes.example.requests.Requests.Request.Protocol protocol_ = com.cscotta.deschutes.example.requests.Requests.Request.Protocol.HTTP;
      /**
       * <code>required .analytics.Request.Protocol protocol = 7;</code>
       */
      public boolean hasProtocol() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required .analytics.Request.Protocol protocol = 7;</code>
       */
      public com.cscotta.deschutes.example.requests.Requests.Request.Protocol getProtocol() {
        return protocol_;
      }
      /**
       * <code>required .analytics.Request.Protocol protocol = 7;</code>
       */
      public Builder setProtocol(com.cscotta.deschutes.example.requests.Requests.Request.Protocol value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .analytics.Request.Protocol protocol = 7;</code>
       */
      public Builder clearProtocol() {
        bitField0_ = (bitField0_ & ~0x00000040);
        protocol_ = com.cscotta.deschutes.example.requests.Requests.Request.Protocol.HTTP;
        onChanged();
        return this;
      }

      // required int32 responseCode = 8;
      private int responseCode_ ;
      /**
       * <code>required int32 responseCode = 8;</code>
       */
      public boolean hasResponseCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 responseCode = 8;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>required int32 responseCode = 8;</code>
       */
      public Builder setResponseCode(int value) {
        bitField0_ |= 0x00000080;
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 responseCode = 8;</code>
       */
      public Builder clearResponseCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        responseCode_ = 0;
        onChanged();
        return this;
      }

      // required string uri = 9;
      private java.lang.Object uri_ = "";
      /**
       * <code>required string uri = 9;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string uri = 9;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uri = 9;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uri = 9;</code>
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 9;</code>
       */
      public Builder clearUri() {
        bitField0_ = (bitField0_ & ~0x00000100);
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>required string uri = 9;</code>
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        uri_ = value;
        onChanged();
        return this;
      }

      // required int32 requestBytes = 10;
      private int requestBytes_ ;
      /**
       * <code>required int32 requestBytes = 10;</code>
       */
      public boolean hasRequestBytes() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 requestBytes = 10;</code>
       */
      public int getRequestBytes() {
        return requestBytes_;
      }
      /**
       * <code>required int32 requestBytes = 10;</code>
       */
      public Builder setRequestBytes(int value) {
        bitField0_ |= 0x00000200;
        requestBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requestBytes = 10;</code>
       */
      public Builder clearRequestBytes() {
        bitField0_ = (bitField0_ & ~0x00000200);
        requestBytes_ = 0;
        onChanged();
        return this;
      }

      // required int32 responseBytes = 11;
      private int responseBytes_ ;
      /**
       * <code>required int32 responseBytes = 11;</code>
       */
      public boolean hasResponseBytes() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 responseBytes = 11;</code>
       */
      public int getResponseBytes() {
        return responseBytes_;
      }
      /**
       * <code>required int32 responseBytes = 11;</code>
       */
      public Builder setResponseBytes(int value) {
        bitField0_ |= 0x00000400;
        responseBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 responseBytes = 11;</code>
       */
      public Builder clearResponseBytes() {
        bitField0_ = (bitField0_ & ~0x00000400);
        responseBytes_ = 0;
        onChanged();
        return this;
      }

      // required int64 handshakeUsec = 12;
      private long handshakeUsec_ ;
      /**
       * <code>required int64 handshakeUsec = 12;</code>
       */
      public boolean hasHandshakeUsec() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required int64 handshakeUsec = 12;</code>
       */
      public long getHandshakeUsec() {
        return handshakeUsec_;
      }
      /**
       * <code>required int64 handshakeUsec = 12;</code>
       */
      public Builder setHandshakeUsec(long value) {
        bitField0_ |= 0x00000800;
        handshakeUsec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 handshakeUsec = 12;</code>
       */
      public Builder clearHandshakeUsec() {
        bitField0_ = (bitField0_ & ~0x00000800);
        handshakeUsec_ = 0L;
        onChanged();
        return this;
      }

      // required int64 usecToFirstByte = 13;
      private long usecToFirstByte_ ;
      /**
       * <code>required int64 usecToFirstByte = 13;</code>
       */
      public boolean hasUsecToFirstByte() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int64 usecToFirstByte = 13;</code>
       */
      public long getUsecToFirstByte() {
        return usecToFirstByte_;
      }
      /**
       * <code>required int64 usecToFirstByte = 13;</code>
       */
      public Builder setUsecToFirstByte(long value) {
        bitField0_ |= 0x00001000;
        usecToFirstByte_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 usecToFirstByte = 13;</code>
       */
      public Builder clearUsecToFirstByte() {
        bitField0_ = (bitField0_ & ~0x00001000);
        usecToFirstByte_ = 0L;
        onChanged();
        return this;
      }

      // required int64 usecTotal = 14;
      private long usecTotal_ ;
      /**
       * <code>required int64 usecTotal = 14;</code>
       */
      public boolean hasUsecTotal() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>required int64 usecTotal = 14;</code>
       */
      public long getUsecTotal() {
        return usecTotal_;
      }
      /**
       * <code>required int64 usecTotal = 14;</code>
       */
      public Builder setUsecTotal(long value) {
        bitField0_ |= 0x00002000;
        usecTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 usecTotal = 14;</code>
       */
      public Builder clearUsecTotal() {
        bitField0_ = (bitField0_ & ~0x00002000);
        usecTotal_ = 0L;
        onChanged();
        return this;
      }

      // optional string userAgent = 15;
      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00004000);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 15;</code>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00004000;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // optional string locale = 16;
      private java.lang.Object locale_ = "";
      /**
       * <code>optional string locale = 16;</code>
       */
      public boolean hasLocale() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string locale = 16;</code>
       */
      public java.lang.String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          locale_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string locale = 16;</code>
       */
      public com.google.protobuf.ByteString
          getLocaleBytes() {
        java.lang.Object ref = locale_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locale_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string locale = 16;</code>
       */
      public Builder setLocale(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        locale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string locale = 16;</code>
       */
      public Builder clearLocale() {
        bitField0_ = (bitField0_ & ~0x00008000);
        locale_ = getDefaultInstance().getLocale();
        onChanged();
        return this;
      }
      /**
       * <code>optional string locale = 16;</code>
       */
      public Builder setLocaleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        locale_ = value;
        onChanged();
        return this;
      }

      // optional string referrer = 17;
      private java.lang.Object referrer_ = "";
      /**
       * <code>optional string referrer = 17;</code>
       */
      public boolean hasReferrer() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional string referrer = 17;</code>
       */
      public java.lang.String getReferrer() {
        java.lang.Object ref = referrer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          referrer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string referrer = 17;</code>
       */
      public com.google.protobuf.ByteString
          getReferrerBytes() {
        java.lang.Object ref = referrer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referrer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string referrer = 17;</code>
       */
      public Builder setReferrer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        referrer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 17;</code>
       */
      public Builder clearReferrer() {
        bitField0_ = (bitField0_ & ~0x00010000);
        referrer_ = getDefaultInstance().getReferrer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string referrer = 17;</code>
       */
      public Builder setReferrerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        referrer_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:analytics.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:analytics.Request)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_analytics_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_analytics_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\tanalytics\"\366\003\n\007Request\022\021" +
      "\n\ttimestamp\030\001 \002(\003\022\020\n\010serverId\030\002 \002(\005\022\016\n\006u" +
      "serId\030\003 \002(\005\022\020\n\010clientIp\030\004 \002(\005\022\020\n\010serverI" +
      "p\030\005 \002(\005\0227\n\roperationType\030\006 \002(\0162 .analyti" +
      "cs.Request.OperationType\022-\n\010protocol\030\007 \002" +
      "(\0162\033.analytics.Request.Protocol\022\024\n\014respo" +
      "nseCode\030\010 \002(\005\022\013\n\003uri\030\t \002(\t\022\024\n\014requestByt" +
      "es\030\n \002(\005\022\025\n\rresponseBytes\030\013 \002(\005\022\025\n\rhands" +
      "hakeUsec\030\014 \002(\003\022\027\n\017usecToFirstByte\030\r \002(\003\022" +
      "\021\n\tusecTotal\030\016 \002(\003\022\021\n\tuserAgent\030\017 \001(\t\022\016\n",
      "\006locale\030\020 \001(\t\022\020\n\010referrer\030\021 \001(\t\"3\n\010Proto" +
      "col\022\010\n\004HTTP\020\000\022\t\n\005HTTPS\020\001\022\010\n\004SPDY\020\002\022\010\n\004QU" +
      "IC\020\003\"-\n\rOperationType\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\022" +
      "\n\n\006DELETE\020\002B(\n\034com.cscotta.deschutes.messa" +
      "gesB\010Requests"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_analytics_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_analytics_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_analytics_Request_descriptor,
              new java.lang.String[] { "Timestamp", "ServerId", "UserId", "ClientIp", "ServerIp", "OperationType", "Protocol", "ResponseCode", "Uri", "RequestBytes", "ResponseBytes", "HandshakeUsec", "UsecToFirstByte", "UsecTotal", "UserAgent", "Locale", "Referrer", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
