package com.cscotta.deschutes.api;

/**
 * An optional wrapper for implementing a flyweight pattern that transforms
 * a raw data input object into an Event (or allows it to act like one) by
 * implementing required methods and providing accessors for its data.
 * Primarily useful when input is generated by IDL (e.g., protobufs), but it
 * is not possible for the IDL object to implement the interface directly.
 * @param <RawInput>
 * @param <WrappedInput>
 */
public interface EventWrapper<RawInput, WrappedInput> {

    public WrappedInput wrap(RawInput raw);

}
